---
name: CMake-Linux-x64

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  ARCHITECTURE: x64

jobs:
  build:
    # if: false  # temporarily disabled
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install -y libopencv-dev
          sudo apt-get install libssl-dev -y
          vcpkg install azure-storage-blobs-cpp azure-identity-cpp

      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DLIBCZI_BUILD_CURL_BASED_STREAM=ON -DLIBCZI_BUILD_AZURESDK_BASED_STREAM=ON -DLIBCZI_BUILD_PREFER_EXTERNALPACKAGE_LIBCURL=ON -DCMAKE_TOOLCHAIN_FILE="${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" ..

      - name: Build
        shell: bash
        run: |
          cd build
          cmake --build . --config "${BUILD_TYPE}" -j "$(nproc)"

      - name: Run Unit-Tests
        shell: bash
        run: |
          cd build
          ctest -C "${BUILD_TYPE}"

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir artifact
          name="czi-pyramidizer-linux-${ARCHITECTURE,,}-$(git describe --always)"
          mkdir "artifact/${name}"
          cp build/czi-pyramidizer/czi-pyramidizer "artifact/${name}/"
          echo "artifactName=${name}" >> "$GITHUB_ENV"
          echo "artifactPath=${{github.workspace}}/artifact/${name}" >> "$GITHUB_ENV"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.artifactPath }}/
          name: ${{ env.artifactName }}
