---
name: CMake-Windows-ARM64

'on':
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  ARCHITECTURE: ARM64

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true  # Tempararily ignore errors in this job, currently it seems the OpenCV build with vcpkg is failing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: 'C:/vcpkg/installed'
          key: vcpkg-arm64-windows-
          restore-keys: |
            vcpkg-arm64-windows-

      - name: Install dependencies
        run: |
          vcpkg install opencv4[core,jpeg,png,quirc,tiff,webp]:arm64-windows-static
          vcpkg install azure-storage-blobs-cpp:arm64-windows-static
          vcpkg install azure-identity-cpp:arm64-windows-static
          vcpkg install 'curl[ssl]' --triplet arm64-windows-static

      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          cd build
          # Configure for a cross-compilation to ARM64.
          # Note that since we are doing a cross compilation, we cannot execute code in order to determine platform
          # characteristics like endianess and whether unaligned access is allowed. Therefore, we need to set the following
          # variables manually: CRASH_ON_UNALIGNED_ACCESS=OFF and IS_BIG_ENDIAN=FALSE.
          cmake -A "${ARCHITECTURE}" \
              -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
              -DCRASH_ON_UNALIGNED_ACCESS=OFF \
              -DIS_BIG_ENDIAN=FALSE \
              -DCZIPYRAMIDIZER_BUILD_UNITTESTS=OFF \
              -DLIBCZI_BUILD_CURL_BASED_STREAM=ON \
              -DLIBCZI_BUILD_AZURESDK_BASED_STREAM=ON \
              -DLIBCZI_BUILD_PREFER_EXTERNALPACKAGE_LIBCURL=ON \
              -DADDITIONAL_LIBS_REQUIRED_FOR_ATOMIC:STRING= \
              -DNEON_INTRINSICS_CAN_BE_USED=TRUE \
              -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DVCPKG_TARGET_TRIPLET=arm64-windows-static ..

      - name: Build
        shell: bash
        run: |
          cd build
          cmake --build . --config "${BUILD_TYPE}" -j

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir artifact
          name="czi-pyramidizer-windows-${ARCHITECTURE,,}-$(git describe --always)"
          mkdir "artifact/${name}"
          cp build/czi-pyramidizer/Release/czi-pyramidizer.exe "artifact/${name}/"
          echo "artifactName=${name}" >> "$GITHUB_ENV"
          echo "artifactPath=${{github.workspace}}/artifact/${name}" >> "$GITHUB_ENV"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.artifactPath }}/
          name: ${{ env.artifactName }}
